"""Gemini writer adapter for mem_bridge.

This module implements writing of canonical :class:`MemoryProfile` objects
into Gemini-compatible output formats.

Gemini supports two primary import/usage formats:

1. **Gem Markdown** (``.md``) – A structured system-prompt document that
   can be pasted directly into a Gem's instruction field in Google Gemini.
   The document includes a user profile section, a memories/facts section,
   and an optional conversation history section.

2. **JSON** (``.json``) – A machine-readable structured object suitable for
   programmatic import or archival.  The schema mirrors the canonical
   :class:`MemoryProfile` structure but uses Gemini-friendly field names.

The output format is selected automatically based on the destination file
extension (``.md`` → markdown, ``.json`` → JSON).  It can also be specified
explicitly via the ``fmt`` parameter on :meth:`GeminiAdapter.write`.

Example usage::

    from mem_bridge.adapters.gemini import GeminiAdapter

    adapter = GeminiAdapter()

    # Write as Gem Markdown
    adapter.write(profile, "my_gem.md")

    # Write as JSON
    adapter.write(profile, "my_gem.json")

    # Render to string without writing to disk
    markdown_str = adapter.render(profile, fmt="markdown")
    json_str     = adapter.render(profile, fmt="json")
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from mem_bridge.models import MemoryProfile, SourcePlatform


class GeminiWriteError(IOError):
    """Raised when the Gemini adapter cannot write an output file."""


# ---------------------------------------------------------------------------
# Markdown template (inline – avoids requiring the template file for the
# adapter to function standalone; the formatters module uses Jinja2 templates
# for richer rendering).
# ---------------------------------------------------------------------------

_MARKDOWN_TEMPLATE = """\
# Memory Profile — {display_name}

> **Source platform:** {source_platform}  
> **Exported at:** {exported_at}  
> **Generated by:** mem_bridge {schema_version}

---

## User Context

You are acting as a personal AI assistant for **{display_name}**.
The following memory facts and conversation history have been imported
from their previous AI assistant. Use this context to personalise your
responses and maintain continuity with prior interactions.

---

## Remembered Facts

{memories_section}

---

## Conversation History

{conversations_section}

---

*This file was generated by [mem_bridge](https://github.com/example/mem_bridge).
Do not edit manually unless you know what you are doing.*
"""

_NO_MEMORIES = "*No memory facts were included in this export.*"
_NO_CONVERSATIONS = "*No conversation history was included in this export.*"


class GeminiAdapter:
    """Writer adapter that exports :class:`MemoryProfile` objects to Gemini-compatible files.

    Supported output formats
    ------------------------
    - ``"markdown"`` / ``"md"`` – Gem Markdown instruction document.
    - ``"json"`` – Structured JSON object.

    The format is auto-detected from the destination file extension when
    :meth:`write` is called.  It can also be forced via the ``fmt`` keyword
    argument.
    """

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def write(
        self,
        profile: MemoryProfile,
        dest: str | Path,
        fmt: str | None = None,
    ) -> None:
        """Serialise *profile* and write it to *dest*.

        The output format is determined by the following priority:

        1. The explicit *fmt* argument (if provided).
        2. The file extension of *dest* (``.md`` → markdown, ``.json`` → JSON).
        3. Falls back to ``"markdown"`` if the extension is unrecognised.

        Parameters
        ----------
        profile:
            The canonical :class:`MemoryProfile` to export.
        dest:
            Destination file path.  Parent directories are created
            automatically if they do not exist.
        fmt:
            Optional format override: ``'markdown'``, ``'md'``, or ``'json'``.

        Raises
        ------
        GeminiWriteError
            If the file cannot be written.
        ValueError
            If an unsupported *fmt* value is provided.
        """
        dest = Path(dest)
        resolved_fmt = self._resolve_format(dest, fmt)
        content = self.render(profile, fmt=resolved_fmt)

        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
        except OSError as exc:
            raise GeminiWriteError(
                f"Failed to write Gemini output to {dest}: {exc}"
            ) from exc

    def render(self, profile: MemoryProfile, fmt: str = "markdown") -> str:
        """Render *profile* to a string in the requested *fmt*.

        Parameters
        ----------
        profile:
            The canonical :class:`MemoryProfile` to render.
        fmt:
            Output format: ``'markdown'``, ``'md'``, or ``'json'``.
            Defaults to ``'markdown'``.

        Returns
        -------
        str
            The rendered output as a UTF-8 string.

        Raises
        ------
        ValueError
            If *fmt* is not a recognised format string.
        """
        fmt = fmt.lower().strip()
        if fmt in ("markdown", "md", "gemini"):
            return self._render_markdown(profile)
        elif fmt == "json":
            return self._render_json(profile)
        else:
            raise ValueError(
                f"Unsupported Gemini output format {fmt!r}. "
                f"Choose 'markdown' or 'json'."
            )

    # ------------------------------------------------------------------
    # Format rendering
    # ------------------------------------------------------------------

    def _render_markdown(self, profile: MemoryProfile) -> str:
        """Render the profile as a Gem Markdown instruction document.

        Parameters
        ----------
        profile:
            Source :class:`MemoryProfile`.

        Returns
        -------
        str
            Formatted Markdown string.
        """
        memories_section = self._build_memories_section(profile)
        conversations_section = self._build_conversations_section(profile)

        exported_at_str = (
            profile.exported_at.strftime("%Y-%m-%d %H:%M UTC")
            if profile.exported_at
            else "unknown"
        )

        output = _MARKDOWN_TEMPLATE.format(
            display_name=_md_escape(profile.display_name),
            source_platform=profile.source_platform.value,
            exported_at=exported_at_str,
            schema_version=profile.schema_version,
            memories_section=memories_section,
            conversations_section=conversations_section,
        )
        return output

    def _render_json(self, profile: MemoryProfile) -> str:
        """Render the profile as a Gemini-friendly JSON string.

        The JSON schema is a thin transformation of the canonical profile,
        using Gemini-friendly field names where they differ.

        Parameters
        ----------
        profile:
            Source :class:`MemoryProfile`.

        Returns
        -------
        str
            Pretty-printed JSON string.
        """
        data = self._build_json_payload(profile)
        return json.dumps(data, indent=2, ensure_ascii=False, default=_json_default)

    # ------------------------------------------------------------------
    # Markdown section builders
    # ------------------------------------------------------------------

    @staticmethod
    def _build_memories_section(profile: MemoryProfile) -> str:
        """Build the '## Remembered Facts' section of the Gem Markdown."""
        if not profile.memories:
            return _NO_MEMORIES

        lines: list[str] = []
        for i, memory in enumerate(profile.memories, start=1):
            content = memory.content.strip()
            tags_str = ""
            if memory.tags:
                tags_str = "  " + " ".join(f"`{t}`" for t in memory.tags)
            lines.append(f"{i}. {content}{tags_str}")

        return "\n".join(lines)

    @staticmethod
    def _build_conversations_section(profile: MemoryProfile) -> str:
        """Build the '## Conversation History' section of the Gem Markdown."""
        if not profile.conversations:
            return _NO_CONVERSATIONS

        blocks: list[str] = []
        for conv in profile.conversations:
            title = conv.title or "Untitled Conversation"
            header = f"### {_md_escape(title)}"

            meta_parts: list[str] = []
            if conv.created_at:
                meta_parts.append(f"*Date: {conv.created_at.strftime('%Y-%m-%d')}*")
            if conv.model:
                meta_parts.append(f"*Model: {conv.model}*")
            meta_line = "  ".join(meta_parts) if meta_parts else ""

            message_lines: list[str] = []
            for entry in conv.entries:
                role_label = entry.role.value.capitalize()
                content = entry.content.strip()
                if not content:
                    continue
                # Indent multi-line content
                indented = content.replace("\n", "\n  > ")
                message_lines.append(f"**{role_label}:** {indented}")

            if not message_lines:
                continue  # Skip empty conversations

            block_parts = [header]
            if meta_line:
                block_parts.append(meta_line)
            block_parts.append("")
            block_parts.extend(message_lines)
            blocks.append("\n".join(block_parts))

        return ("\n\n".join(blocks)) if blocks else _NO_CONVERSATIONS

    # ------------------------------------------------------------------
    # JSON payload builder
    # ------------------------------------------------------------------

    @staticmethod
    def _build_json_payload(profile: MemoryProfile) -> dict[str, Any]:
        """Construct the Gemini JSON payload from a :class:`MemoryProfile`.

        Parameters
        ----------
        profile:
            Source :class:`MemoryProfile`.

        Returns
        -------
        dict[str, Any]
            A plain dictionary ready for JSON serialisation.
        """
        payload: dict[str, Any] = {
            "gem_format_version": "1.0",
            "generated_by": "mem_bridge",
            "generated_at": datetime.now(tz=timezone.utc).isoformat(),
            "user": {
                "display_name": profile.display_name,
                "source_platform": profile.source_platform.value,
                "exported_at": (
                    profile.exported_at.isoformat()
                    if profile.exported_at
                    else None
                ),
            },
            "memory_facts": [
                {
                    "id": memory.id,
                    "content": memory.content,
                    "tags": memory.tags,
                    "created_at": (
                        memory.created_at.isoformat()
                        if memory.created_at
                        else None
                    ),
                    "updated_at": (
                        memory.updated_at.isoformat()
                        if memory.updated_at
                        else None
                    ),
                }
                for memory in profile.memories
            ],
            "conversation_history": [
                {
                    "id": conv.id,
                    "title": conv.title,
                    "model": conv.model,
                    "created_at": (
                        conv.created_at.isoformat()
                        if conv.created_at
                        else None
                    ),
                    "updated_at": (
                        conv.updated_at.isoformat()
                        if conv.updated_at
                        else None
                    ),
                    "messages": [
                        {
                            "id": entry.id,
                            "role": entry.role.value,
                            "content": entry.content,
                            "timestamp": (
                                entry.timestamp.isoformat()
                                if entry.timestamp
                                else None
                            ),
                            "model": entry.model,
                        }
                        for entry in conv.entries
                    ],
                }
                for conv in profile.conversations
            ],
            "statistics": {
                "memory_count": profile.memory_count,
                "conversation_count": profile.conversation_count,
                "total_message_count": profile.total_message_count,
            },
        }
        return payload

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    @staticmethod
    def _resolve_format(dest: Path, fmt: str | None) -> str:
        """Determine the output format from *fmt* override or *dest* extension.

        Parameters
        ----------
        dest:
            Destination file path.
        fmt:
            Explicit format override, or ``None``.

        Returns
        -------
        str
            One of ``'markdown'`` or ``'json'``.

        Raises
        ------
        ValueError
            If an explicit *fmt* is provided but is not supported.
        """
        if fmt is not None:
            fmt_lower = fmt.lower().strip()
            if fmt_lower in ("markdown", "md", "gemini"):
                return "markdown"
            elif fmt_lower == "json":
                return "json"
            else:
                raise ValueError(
                    f"Unsupported Gemini output format {fmt!r}. "
                    f"Choose 'markdown' or 'json'."
                )

        # Auto-detect from extension
        suffix = dest.suffix.lower()
        if suffix == ".json":
            return "json"
        # Default to markdown for .md, .txt, or anything else
        return "markdown"


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------


def _md_escape(text: str) -> str:
    """Escape Markdown special characters in *text* for safe inline use.

    Only escapes characters that could alter rendered output when appearing
    in headings or inline text: backticks, asterisks, underscores, and pipes.

    Parameters
    ----------
    text:
        Plain-text string to escape.

    Returns
    -------
    str
        Markdown-safe string.
    """
    # Escape the most disruptive Markdown special chars in names/titles
    for char in ("|", "*", "_", "`", "[", "]"):
        text = text.replace(char, f"\\{char}")
    return text


def _json_default(obj: Any) -> Any:
    """JSON serialisation fallback for non-standard types.

    Parameters
    ----------
    obj:
        Object that the default JSON encoder cannot serialise.

    Returns
    -------
    Any
        A JSON-serialisable representation.

    Raises
    ------
    TypeError
        If the object type cannot be handled.
    """
    if isinstance(obj, datetime):
        return obj.isoformat()
    raise TypeError(f"Object of type {type(obj).__name__} is not JSON serialisable")


__all__ = ["GeminiAdapter", "GeminiWriteError"]
