"""Output formatters for mem_bridge.

This module provides functions and a ``Formatter`` class that render a
:class:`~mem_bridge.models.MemoryProfile` into one of several output formats:

- **markdown** – A structured system prompt rendered via a Jinja2 template,
  suitable for pasting into an LLM's system prompt field.
- **json** – Pretty-printed JSON representation of the canonical profile.
- **yaml** – YAML representation of the canonical profile.
- **text** – A concise plain-text summary suitable for terminal display.
- **gemini** – Alias for the Gemini Gem Markdown format (delegates to
  :class:`~mem_bridge.adapters.gemini.GeminiAdapter`).

The primary entry point is the module-level :func:`render` function::

    from mem_bridge.formatters import render
    from mem_bridge.models import MemoryProfile

    profile = MemoryProfile(...)
    markdown_str = render(profile, fmt="markdown")
    json_str     = render(profile, fmt="json")
    yaml_str     = render(profile, fmt="yaml")
    text_str     = render(profile, fmt="text")

Custom Jinja2 environments and template directories can be supplied via the
:class:`Formatter` class for more advanced use cases.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any

import yaml
from jinja2 import (
    Environment,
    FileSystemLoader,
    PackageLoader,
    StrictUndefined,
    Template,
    TemplateNotFound,
    select_autoescape,
)

from mem_bridge.models import MemoryProfile, OutputFormat, Role


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Default templates directory (relative to the project root)
_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

# Fallback inline Jinja2 template used when the templates directory or
# prompt.md.j2 file is not found on disk.
_FALLBACK_PROMPT_TEMPLATE = """\
# AI Memory Profile — {{ profile.display_name }}

> **Source:** {{ profile.source_platform.value }}  \
{% if profile.exported_at %}
> **Exported:** {{ profile.exported_at.strftime('%Y-%m-%d %H:%M UTC') }}  \
{% endif %}
> **Memories:** {{ profile.memory_count }}  \
> **Conversations:** {{ profile.conversation_count }}

---

## System Context

You are a helpful AI assistant continuing a conversation with **{{ profile.display_name }}**.
The following facts and conversation history have been imported from a previous AI session.
Use this information to maintain context and personalise your responses.

---
{% if profile.memories %}

## Remembered Facts

{% for memory in profile.memories %}
{{ loop.index }}. {{ memory.content }}\
{% if memory.tags %} *({{ memory.tags | join(', ') }})*{% endif %}
{% endfor %}
{% else %}

## Remembered Facts

*No memory facts available in this profile.*
{% endif %}

---
{% if profile.conversations %}

## Conversation History

{% for conv in profile.conversations %}
### {{ conv.title | default('Untitled Conversation') }}
{% if conv.created_at %}*Date: {{ conv.created_at.strftime('%Y-%m-%d') }}*  {% endif %}\
{% if conv.model %}*Model: {{ conv.model }}*{% endif %}

{% for entry in conv.entries %}\
{% if entry.content.strip() %}
**{{ entry.role.value | capitalize }}:** {{ entry.content.strip() }}
{% endif %}\
{% endfor %}
{% endfor %}
{% else %}

## Conversation History

*No conversation history available in this profile.*
{% endif %}

---

*Generated by mem_bridge {{ profile.schema_version }}.*
"""


# ---------------------------------------------------------------------------
# Helper filter functions for Jinja2
# ---------------------------------------------------------------------------


def _wrap_text(text: str, width: int = 80) -> str:
    """Word-wrap *text* to *width* characters."""
    return textwrap.fill(text, width=width)


def _truncate(text: str, length: int = 120, suffix: str = "...") -> str:
    """Truncate *text* to *length* characters, appending *suffix* if trimmed."""
    if len(text) <= length:
        return text
    return text[: length - len(suffix)].rstrip() + suffix


def _format_datetime(value: Any, fmt: str = "%Y-%m-%d %H:%M UTC") -> str:
    """Format a datetime object to a string; return 'N/A' if None."""
    if value is None:
        return "N/A"
    try:
        return value.strftime(fmt)
    except (AttributeError, ValueError):
        return str(value)


def _role_label(role: Role) -> str:
    """Convert a :class:`~mem_bridge.models.Role` to a display label."""
    labels = {
        Role.USER: "User",
        Role.ASSISTANT: "Assistant",
        Role.SYSTEM: "System",
        Role.TOOL: "Tool",
        Role.UNKNOWN: "Unknown",
    }
    return labels.get(role, role.value.capitalize())


# ---------------------------------------------------------------------------
# Formatter class
# ---------------------------------------------------------------------------


class Formatter:
    """Renders :class:`~mem_bridge.models.MemoryProfile` objects to multiple formats.

    Parameters
    ----------
    templates_dir:
        Path to the directory containing Jinja2 template files.  If not
        supplied, the default ``templates/`` directory at the project root
        is used.  If that directory does not exist either, a built-in
        fallback template is used.
    strict:
        If ``True`` (default), undefined Jinja2 variables raise an error.
        Set to ``False`` to silently ignore undefined variables.

    Example
    -------
    ::

        formatter = Formatter()
        md = formatter.render(profile, fmt="markdown")
        print(md)
    """

    def __init__(
        self,
        templates_dir: str | Path | None = None,
        strict: bool = True,
    ) -> None:
        self._templates_dir = Path(templates_dir) if templates_dir else _TEMPLATES_DIR
        self._strict = strict
        self._env: Environment | None = None
        self._fallback_template: Template | None = None

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def render(self, profile: MemoryProfile, fmt: str = "markdown") -> str:
        """Render *profile* to the requested output *fmt*.

        Parameters
        ----------
        profile:
            The canonical :class:`~mem_bridge.models.MemoryProfile` to render.
        fmt:
            One of ``'markdown'``, ``'json'``, ``'yaml'``, ``'text'``,
            or ``'gemini'``.  Case-insensitive.

        Returns
        -------
        str
            Rendered output as a UTF-8 string.

        Raises
        ------
        ValueError
            If *fmt* is not a recognised format string.
        """
        fmt_lower = fmt.lower().strip()

        if fmt_lower in ("markdown", "md"):
            return self._render_markdown(profile)
        elif fmt_lower == "json":
            return self._render_json(profile)
        elif fmt_lower == "yaml":
            return self._render_yaml(profile)
        elif fmt_lower == "text":
            return self._render_text(profile)
        elif fmt_lower == "gemini":
            return self._render_gemini(profile)
        else:
            supported = [f.value for f in OutputFormat]
            raise ValueError(
                f"Unsupported format {fmt!r}. "
                f"Supported formats: {supported}."
            )

    def render_to_file(
        self,
        profile: MemoryProfile,
        dest: str | Path,
        fmt: str | None = None,
    ) -> None:
        """Render *profile* and write the result to *dest*.

        The output format is determined by *fmt* if given, otherwise
        auto-detected from the file extension of *dest*.

        Parameters
        ----------
        profile:
            The canonical :class:`~mem_bridge.models.MemoryProfile` to render.
        dest:
            Destination file path.  Parent directories are created
            automatically if they do not exist.
        fmt:
            Optional explicit format override.  If ``None``, the format is
            inferred from the file extension.

        Raises
        ------
        ValueError
            If the format cannot be determined or is not supported.
        IOError
            If the file cannot be written.
        """
        dest = Path(dest)
        resolved_fmt = fmt or self._infer_format_from_path(dest)
        content = self.render(profile, fmt=resolved_fmt)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")

    # ------------------------------------------------------------------
    # Format-specific renderers
    # ------------------------------------------------------------------

    def _render_markdown(self, profile: MemoryProfile) -> str:
        """Render *profile* using the Jinja2 prompt template."""
        template = self._get_prompt_template()
        return template.render(
            profile=profile,
            wrap=_wrap_text,
            truncate=_truncate,
            format_dt=_format_datetime,
            role_label=_role_label,
        )

    @staticmethod
    def _render_json(profile: MemoryProfile) -> str:
        """Render *profile* as pretty-printed JSON."""
        return profile.to_json(indent=2)

    @staticmethod
    def _render_yaml(profile: MemoryProfile) -> str:
        """Render *profile* as YAML."""
        return profile.to_yaml()

    def _render_text(self, profile: MemoryProfile) -> str:
        """Render *profile* as a concise plain-text summary."""
        lines: list[str] = []

        # Header
        lines.append("=" * 60)
        lines.append(f"Memory Profile: {profile.display_name}")
        lines.append("=" * 60)
        lines.append(f"Source platform : {profile.source_platform.value}")
        if profile.exported_at:
            lines.append(
                f"Exported at     : {profile.exported_at.strftime('%Y-%m-%d %H:%M UTC')}"
            )
        lines.append(f"Schema version  : {profile.schema_version}")
        lines.append(f"Memories        : {profile.memory_count}")
        lines.append(f"Conversations   : {profile.conversation_count}")
        lines.append(f"Total messages  : {profile.total_message_count}")
        lines.append("")

        # Memories
        lines.append("-" * 60)
        lines.append("REMEMBERED FACTS")
        lines.append("-" * 60)
        if profile.memories:
            for i, mem in enumerate(profile.memories, start=1):
                content = _truncate(mem.content, length=100)
                tag_str = f" [{', '.join(mem.tags)}]" if mem.tags else ""
                lines.append(f"{i:3}. {content}{tag_str}")
        else:
            lines.append("  (none)")
        lines.append("")

        # Conversations
        lines.append("-" * 60)
        lines.append("CONVERSATIONS")
        lines.append("-" * 60)
        if profile.conversations:
            for i, conv in enumerate(profile.conversations, start=1):
                title = _truncate(conv.title, length=55)
                date_str = (
                    conv.created_at.strftime("%Y-%m-%d") if conv.created_at else "unknown date"
                )
                model_str = f" [{conv.model}]" if conv.model else ""
                lines.append(
                    f"{i:3}. {title} ({date_str}, {conv.message_count} msgs{model_str})"
                )
        else:
            lines.append("  (none)")
        lines.append("")
        lines.append("=" * 60)

        return "\n".join(lines)

    @staticmethod
    def _render_gemini(profile: MemoryProfile) -> str:
        """Render *profile* using the Gemini adapter's Markdown renderer."""
        from mem_bridge.adapters.gemini import GeminiAdapter

        adapter = GeminiAdapter()
        return adapter.render(profile, fmt="markdown")

    # ------------------------------------------------------------------
    # Jinja2 environment helpers
    # ------------------------------------------------------------------

    def _get_env(self) -> Environment:
        """Return a cached :class:`jinja2.Environment` for the templates directory."""
        if self._env is None:
            undefined_cls = StrictUndefined if self._strict else StrictUndefined
            if self._templates_dir.is_dir():
                self._env = Environment(
                    loader=FileSystemLoader(str(self._templates_dir)),
                    autoescape=select_autoescape([]),
                    undefined=undefined_cls,
                    trim_blocks=True,
                    lstrip_blocks=True,
                    keep_trailing_newline=True,
                )
            else:
                # No templates directory – create an env with no loader;
                # _get_prompt_template will fall back to the inline template.
                self._env = Environment(
                    undefined=undefined_cls,
                    trim_blocks=True,
                    lstrip_blocks=True,
                    keep_trailing_newline=True,
                )
            # Register custom filters
            self._env.filters["wrap"] = _wrap_text
            self._env.filters["truncate_text"] = _truncate
            self._env.filters["format_dt"] = _format_datetime
            self._env.filters["role_label"] = _role_label
        return self._env

    def _get_prompt_template(self) -> Template:
        """Return the Jinja2 template for Markdown prompt rendering.

        Resolution order:

        1. ``<templates_dir>/prompt.md.j2`` on disk.
        2. The built-in fallback inline template.

        Returns
        -------
        Template
            A ready-to-render Jinja2 :class:`~jinja2.Template` object.
        """
        env = self._get_env()

        # Try to load from the file system first
        if self._templates_dir.is_dir():
            template_path = self._templates_dir / "prompt.md.j2"
            if template_path.exists():
                try:
                    return env.get_template("prompt.md.j2")
                except TemplateNotFound:
                    pass

        # Fall back to the inline template
        if self._fallback_template is None:
            self._fallback_template = Environment(
                undefined=StrictUndefined,
                trim_blocks=True,
                lstrip_blocks=True,
                keep_trailing_newline=True,
            ).from_string(_FALLBACK_PROMPT_TEMPLATE)
        return self._fallback_template

    # ------------------------------------------------------------------
    # Utility
    # ------------------------------------------------------------------

    @staticmethod
    def _infer_format_from_path(path: Path) -> str:
        """Infer an output format string from a file path's extension.

        Parameters
        ----------
        path:
            Destination file path.

        Returns
        -------
        str
            One of ``'markdown'``, ``'json'``, ``'yaml'``, or ``'text'``.
        """
        suffix = path.suffix.lower()
        mapping = {
            ".md": "markdown",
            ".markdown": "markdown",
            ".json": "json",
            ".yaml": "yaml",
            ".yml": "yaml",
            ".txt": "text",
        }
        return mapping.get(suffix, "markdown")


# ---------------------------------------------------------------------------
# Module-level convenience API
# ---------------------------------------------------------------------------

# Shared default formatter instance
_default_formatter = Formatter()


def render(profile: MemoryProfile, fmt: str = "markdown") -> str:
    """Render *profile* to the requested output format.

    This is a convenience wrapper around :class:`Formatter`.  For most use
    cases it is sufficient to call this function directly.

    Parameters
    ----------
    profile:
        The canonical :class:`~mem_bridge.models.MemoryProfile` to render.
    fmt:
        Output format.  One of:

        * ``'markdown'`` or ``'md'`` – Structured system prompt (Jinja2 template).
        * ``'json'`` – Pretty-printed JSON.
        * ``'yaml'`` – YAML.
        * ``'text'`` – Concise plain-text summary.
        * ``'gemini'`` – Gemini Gem Markdown (via the Gemini adapter).

        Case-insensitive.  Defaults to ``'markdown'``.

    Returns
    -------
    str
        Rendered output as a UTF-8 string.

    Raises
    ------
    ValueError
        If *fmt* is not a recognised format string.

    Examples
    --------
    ::

        from mem_bridge.formatters import render
        from mem_bridge.models import MemoryProfile

        profile = MemoryProfile(display_name="Alice")
        print(render(profile, fmt="text"))
    """
    return _default_formatter.render(profile, fmt=fmt)


def render_to_file(
    profile: MemoryProfile,
    dest: str | Path,
    fmt: str | None = None,
) -> None:
    """Render *profile* and write it to *dest*.

    The output format is determined by *fmt* if given; otherwise it is
    inferred from the file extension of *dest*.

    Parameters
    ----------
    profile:
        The canonical :class:`~mem_bridge.models.MemoryProfile` to render.
    dest:
        Destination file path.  Parent directories are created automatically.
    fmt:
        Optional explicit format override (see :func:`render` for valid
        values).  If ``None``, the format is inferred from the file extension.

    Raises
    ------
    ValueError
        If the format cannot be determined or is not supported.
    IOError
        If the file cannot be written.
    """
    _default_formatter.render_to_file(profile, dest, fmt=fmt)


def list_formats() -> list[str]:
    """Return a sorted list of all supported output format names.

    Returns
    -------
    list[str]
        Sorted list of format identifier strings.

    Example
    -------
    ::

        >>> from mem_bridge.formatters import list_formats
        >>> list_formats()
        ['gemini', 'json', 'markdown', 'text', 'yaml']
    """
    return sorted(f.value for f in OutputFormat)


def get_format_description(fmt: str) -> str:
    """Return a human-readable description for a given output format.

    Parameters
    ----------
    fmt:
        Format identifier string (case-insensitive).

    Returns
    -------
    str
        Human-readable description.

    Raises
    ------
    ValueError
        If *fmt* is not a recognised format.
    """
    descriptions = {
        "markdown": "Structured system prompt rendered via Jinja2 template (Markdown).",
        "json": "Pretty-printed JSON representation of the canonical MemoryProfile.",
        "yaml": "YAML representation of the canonical MemoryProfile.",
        "text": "Concise plain-text summary suitable for terminal display.",
        "gemini": "Gemini Gem Markdown instruction document (via Gemini adapter).",
    }
    fmt_lower = fmt.lower().strip()
    if fmt_lower not in descriptions:
        raise ValueError(
            f"Unsupported format {fmt!r}. "
            f"Supported formats: {sorted(descriptions)}."
        )
    return descriptions[fmt_lower]


__all__ = [
    "Formatter",
    "get_format_description",
    "list_formats",
    "render",
    "render_to_file",
]
